language: go

go:
  - 1.11
  - 1.11.4
  - tip

sudo: false

before_install:
  - export GO15VENDOREXPERIMENT=1
  - RepoName=`basename $PWD`; SrcDir=`dirname $PWD`; DestDir="`dirname $SrcDir`/stackanetes"
  - if [[ "$SrcDir" != "$DestDir" ]]; then mv "$SrcDir" "$DestDir"; cd ../../stackanetes/$RepoName; export TRAVIS_BUILD_DIR=`dirname $TRAVIS_BUILD_DIR`/$RepoName; fi

install:
  - echo 'nop'

script:
  - go test -v $(go list ./... | grep -v /vendor/)

notifications:
  email: false

matrix:
  allow_failures:
    - go: tip
